import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>zackpiper.com</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <main>
        <h1>Hello, world!</h1>
      </main>

      <footer>
        <p>© {new Date().getFullYear()} Zack Piper</p>
      </footer>
    </div>
  )
}

export default Home
