import type { NextPage } from 'next'
import Head from 'next/head'
import { Typography } from '@mui/material'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>zackpiper.com | home</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <main>
        <Typography variant="h1">Hello, world!</Typography>
      </main>

      <footer>
        <p>© {new Date().getFullYear()} Zack Piper</p>
      </footer>
    </div>
  )
}

export default Home
